### ISSUE TITLE
Figure out how to detect cycles/not allow them

### ISSUE THREAD

**Issue by chanceraine** [chanceraine/ARL_Site#12]

**Comment by monocleman** [comment]
ug this might actually be not that trivial.  Floyd's algorithm...here we come!

Not sure if yall remember this from 314: basically run through the linked list (in this case, that's the list that goes parentList -> childList) with two iterators, one taking one step for every two steps of the other one, checking for node equivalency at each step.  Woohoo!

**Comment by monocleman** [comment]
Floyd's algorithm wasn't necessary; we only had to ensure that any lists added to the current list didn't contain the current list; adding children multiple times is fine as long as they aren't in the same chain together.
